### ISSUE TITLE
Nested list spacing looks incorrect

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-frontend#430]
When creating a nested list, the spacing for the nested `<ul>` and `<li>` elements doesn't look right. I think there needs to be some top margin adding to either the nested `<ul>` or`<li>` items and the bottom margin removed from the nested `<ul>` 

**Example:**

<img width="727" alt="Screenshot 2019-04-01 at 14 58 40" src="https://user-images.githubusercontent.com/11615501/55333197-b4633300-548e-11e9-9c25-1f7dbcba4ca2.png">

**Markup:**

```
<ul>
  <li><a href="/">Home</a></li>
  <li>
    <a href="/our-policies">Our policies</a>
    <ul>
      <li><a href="/our-policies/cookies">Cookies</a></li>
      <li><a href="/our-policies/terms-and-conditions">Terms and conditions</a></li>
      <li><a href="/our-policies/privacy-policy">Privacy policy</a></li>
      <li><a href="/our-policies/accessibility">Accessibility</a></li>
    </ul>
  </li>
  <li><a href="/sitemap">Sitemap</a></li>
</ul>
```

**Potential fix:**

Created as a utility class as a hotfix. 
(This goes against the single direction margin rule, so will need to be tweaked)

**SCSS:**

```
.nhsuk-u-nested-list {
  margin-bottom: 0;
}

.nhsuk-u-nested-list > li {
  @include nhsuk-responsive-margin(2, 'top');
}
```

**Markup:**

```
<ul>
  <li><a href="/">Home</a></li>
  <li>
    <a href="/our-policies">Our policies</a>
    <ul class="nhsuk-u-nested-list">
      <li><a href="/our-policies/cookies">Cookies</a></li>
      <li><a href="/our-policies/terms-and-conditions">Terms and conditions</a></li>
      <li><a href="/our-policies/privacy-policy">Privacy policy</a></li>
      <li><a href="/our-policies/accessibility">Accessibility</a></li>
    </ul>
  </li>
  <li><a href="/sitemap">Sitemap</a></li>
</ul>
```

**Example:**

<img width="847" alt="Screenshot 2019-04-01 at 15 02 57" src="https://user-images.githubusercontent.com/11615501/55333437-41a68780-548f-11e9-8142-34053a041ef9.png">

**Comment by GrilloPress** [comment]
Could you do something like:

```scss
li:last-of-type ul::before {

  content: "";
  display: block;
  @include nhsuk-responsive-margin(2, 'bottom');  // or $whateverTheRightVariableIsMate
}
```

this way it injects a pseudo element before the next list and creates the margin.

Feels a touch "over-engineery" though

Example with this code:

![image](https://user-images.githubusercontent.com/5756226/56810182-8a9ef100-682d-11e9-88eb-4008d0ad1811.png)

**Comment by AdamChrimes** [comment]
@GrilloPress I wonder if we can use the Adjacent sibling combinator selector instead? https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator

```
ul + ul {
  @include nhsuk-responsive-margin(2, 'bottom');  // or $whateverTheRightVariableIsMate
}
```

**Comment by GrilloPress** [comment]
This is what I'm currently doing in my kit (now):

```SCSS
li ul {
  margin-bottom: 0;

  &::before {
    content: "";
    display: block;
    @include nhsuk-responsive-margin(2, 'bottom');  // or $whateverTheRightVariableIsMate

  }
}
```

Seems to work fine and handles ULs within ULs as the last item or in the middle of a complex list
