### ISSUE TITLE
Search input: focus state style (mobile)

### ISSUE THREAD

**Issue by idiosyn** [nhsuk/nhsuk-frontend#675]
## Problem

The search input focus state style on mobile is:

``` css
@media (max-width: 40.0525em) {
   .autocomplete__input:focus {
      border: 4px solid #ffeb3b;
      box-shadow: inset 0 0 0 4px #212b32;
      outline: 4px solid transparent;
      outline-offset: 4px;
   }
}
```

This causes the text to jump a bit when the field receives focus (perhaps similarly to issue https://github.com/nhsuk/nhsuk-frontend/issues/613).

![search-mobile-focus-original](https://user-images.githubusercontent.com/38734779/103238788-82fced00-492a-11eb-8e6e-63c751021058.gif)

Using `outline` rather than `border` (as it was done for regular text inputs in PR https://github.com/nhsuk/nhsuk-frontend/pull/614) is not possible because the search field border has rounded corners (`outline` does not allow that).

I have two suggestions.

## Suggestion 1: Adjust padding

We can simply adjust `padding` to make up for the thicker border.

![search-mobile-focus-s1](https://user-images.githubusercontent.com/38734779/103238813-990aad80-492a-11eb-85d1-414589a5208d.gif)

See last line:

``` css
@media (max-width: 40.0525em) {
   .autocomplete__input:focus {
      border: 4px solid #ffeb3b;
      box-shadow: inset 0 0 0 4px #212b32;
      outline: 4px solid transparent;
      outline-offset: 4px;
      padding: 0 13px;
   }
}
```

## Suggestion 2: Desktop style

On desktop, the search input focus state style does not have a black `border` or `box-shadow`. We can simply remove the media queries and apply the same style to mobile.

![search-mobile-focus-s2](https://user-images.githubusercontent.com/38734779/103238822-9e67f800-492a-11eb-8d4f-a4c1c34f1fe7.gif)

``` css
.autocomplete__input:focus {
   border: 1px solid #ffeb3b;
   box-shadow: inset 0 0 0 4px #ffeb3b;
   outline: 4px solid transparent;
   outline-offset: 4px;
}
```
